# Generated by Django 2.2.13 on 2021-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
