# Generated by Django 2.2.13 on 2021-11-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
