# Generated by Django 2.2.13 on 2021-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211102_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
