# Generated by Django 2.2.13 on 2021-11-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
