# Generated by Django 2.2.13 on 2021-11-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
