# Generated by Django 2.2.13 on 2021-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdetails_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='finger_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_authentication',
            field=models.CharField(blank=True, choices=[('1', 'FACE AUTHENTICATION'), ('2', 'FINGER PRINT AUTHENTICATION'), ('3', 'PHONE AUTHENTICATION')], max_length=1, null=True),
        ),
    ]
